### ISSUE TITLE
Implementación de API

### ISSUE THREAD

**Issue by CamilaLozanoValle** [ISCOUTB/AG-AgricultureCompany#17]
Implementación necesaria para el funcionamiento del sistema en su totalidad mediante la API.

**Comment by mogi22210** [comment]
Se evidencia la funcionalidad e implementación de la API de FastAPI en nuestra app.

**Comment by mogi22210** [comment]
![Image](https://github.com/user-attachments/assets/3185c8c0-1a6f-43a7-b8b0-b8343e0aef41)
