### ISSUE TITLE
Revisión del tipo de datos (relacional o no relacional)

### ISSUE THREAD

**Issue by CamilaLozanoValle** [ISCOUTB/AG-AgricultureCompany#19]
Determinar que tipo de datos son relacionales y cuales son no relacionales

**Comment by mogi22210** [comment]
Escogimos PostgreSQL porque todas nuestras entidades serán gestionadas de manera relacional, lo que se alinea perfectamente con sus capacidades. Además, PostgreSQL es una tecnología de código abierto, amigable y fácil de comprender. Es gratuita y se ajusta bien al manejo de nuestras entidades: Cultivo, Cosecha, Silo, Punto de Venta, Encargo, Vehículo y Venta. Este motor hace que la vinculación entre estas entidades no presente complejidad significativa..

**Comment by jairoserrano** [comment]
ok adelante
